### ISSUE TITLE
Source code of preprocessing dataset

### ISSUE THREAD

**Issue by chronbird** [alex-xun-xu/WeakSupPointCloudSeg#2]
Hi,

Thanks for the great work! I want to ask how the .mat files in the Dataset folder are generated? Is there any source code to check? Thanks in advance.

**Comment by alex-xun-xu** [comment]
I randomly sample m% points from each category, e.g. wing, engine, etc. in the plane shape. You could visualize the sampled points to get a sense. I will try to upload the sampling function soon.
