### ISSUE TITLE
IndexError: index 4 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by reluuu** [alex-xun-xu/WeakSupPointCloudSeg#3]
Hi, thanks for the great work.
I want to use the 'plain' module in the code, but an error occurred. How should I change the code?

![image](https://user-images.githubusercontent.com/46579108/90855597-9b8a4480-e345-11ea-9916-003963eddd91.png)
Thanks a lot!

**Comment by alex-xun-xu** [comment]
> Hi, thanks for the great work.
> I want to use the 'plain' module in the code, but an error occurred. How should I change the code?
> 
> ![image](https://user-images.githubusercontent.com/46579108/90855597-9b8a4480-e345-11ea-9916-003963eddd91.png)
> Thanks a lot!

Thanks so much for reporting this bug. I forgot to remove the "2 *" in the plain training function. Please try the update version.
